name: "deploy02"
on:
  workflow_dispatch:
jobs:
  deploy-to:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: '{"clientId":"${{ secrets.client_id }}","clientSecret":"${{ secrets.client_secret }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1.0.8
        with:
          scope: resourcegroup
          resourceGroupName: "${{ vars.resource_group }}"
          template: "ARM-Templates/container-webapp-template.json"
          deploymentMode: Incremental
          
  
  
  
